#!/usr/bin/env python3
"""Serialize an offline GPU fit into the fixed, versioned Rust table contract."""
import argparse
import hashlib
import json
from pathlib import Path

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('fit', type=Path)
parser.add_argument('output', type=Path)
args = parser.parse_args()
fit = json.loads(args.fit.read_text())
root = Path(__file__).resolve().parent.parent
assert fit['version'] == 1
axes = [('SIGMAS', 'sigmas', 11), ('BRIGHTNESS', 'brightness', 7),
        ('DETAILS', 'details', 3), ('STEPS', 'steps', 5)]
lines = ['// Generated by bench/generate-denoise-tables.py from production-GPU fitting.',
         '// Shader SHA-256: ' + hashlib.sha256((root / 'src-tauri/src/shaders/shader.wgsl').read_bytes()).hexdigest(),
         'pub const VERSION: u32 = 1;', 'pub const MEASUREMENT_VERSION: u32 = 3;']
for name, key, size in axes:
    assert len(fit[key]) == size and all(a < b for a, b in zip(fit[key], fit[key][1:]))
    values = []
    for value in fit[key]:
        v = format(value, '.9g')
        values.append(v if '.' in v or 'e' in v else v + '.0')
    lines.append(f'pub const {name}: [f32; {size}] = [{", ".join(values)}];')
for name, size in [('strength', 3), ('chroma', 5)]:
    table = fit[name]
    assert len(table) == 7
    lines.append(f'pub const {name.upper()}: [[[Option<u8>; 11]; {size}]; 7] = [')
    for brightness in table:
        assert len(brightness) == size
        lines.append('[')
        for row in brightness:
            assert len(row) == 11
            assert all(v is None or type(v) is int and 0 <= v <= 100 for v in row)
            lines.append('[' + ', '.join('None' if v is None else f'Some({v})' for v in row) + '],')
        lines.append('],')
    lines.append('];')
args.output.parent.mkdir(parents=True, exist_ok=True)
args.output.write_text('\n'.join(lines) + '\n')
